### ISSUE TITLE
Logstash amazon_es output plugin silently fails with IAM role auth

### ISSUE THREAD

**Issue by phundisk** [awslabs/logstash-output-amazon_es#85] opened 2018-05-25 20:05 UTC
When using the amazon_es output plugin to AWS ElasticSearch using IAM role auth, everything appears to be working from a logging point of view, however, it appears we never see any data in the index nor do we ever see any error indicating that the data is failing to to be sent to the es index.  When using no authentication on the ES cluster and output plugin of just 'elasticsearch', everything works just fine.  Anyone have any ideas what may be going on here or ideas to better debug?  I have attached all configuration from various components here.  I have also tried the case of configuring the aws_access_key_id and aws_secret_access_key of a user directly and that also did not seem to work. 

Logs of the logstash agent here in debug mode... 
```
[2018-05-25T19:48:54,910][DEBUG][logstash.pipeline        ] filter received {"event"=>{"tags"=>["_grokparsefailure_sysloginput"], "@timestamp"=>2018-05-25T19:48:54.809Z, "host"=>"172.16.0.247", "message"=>"<14> May 25 15:46:44 172.16.0.247 00077 ports:  ST1-CMDR: port 1/15 is now off-line", "priority"=>0, "severity"=>0, "facility"=>0, "severity_label"=>"Emergency", "@version"=>"1", "facility_label"=>"kernel"}}
[2018-05-25T19:48:54,910][DEBUG][logstash.pipeline        ] output received {"event"=>{"tags"=>["_grokparsefailure_sysloginput"], "@timestamp"=>2018-05-25T19:48:54.809Z, "host"=>"172.16.0.247", "message"=>"<14> May 25 15:46:44 172.16.0.247 00077 ports:  ST1-CMDR: port 1/15 is now off-line", "priority"=>0, "severity"=>0, "facility"=>0, "severity_label"=>"Emergency", "@version"=>"1", "facility_label"=>"kernel"}}
[2018-05-25T19:48:54,911][DEBUG][logstash.outputs.amazones] Flushing output {:outgoing_count=>1, :time_since_last_flush=>94.366061, :outgoing_events=>{nil=>[["index", {:_id=>nil, :_index=>"logstash-2018.05.25", :_type=>"logs", :_routing=>nil}, #<LogStash::Event:0x68a5dba5>]]}, :batch_timeout=>1, :force=>nil, :final=>nil}
```

I have AWS ES configured with the following...
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::xxx:role/logstash",
          "arn:aws:iam::xxx:role/service-role/CognitoAccessForAmazonES",
          "arn:aws:sts::xxx:assumed-role/CognitoRole/CognitoIdentityCredentials"
        ]
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:us-east-1:xxx:domain/yyy/*"
    }
  ]
}
```

I have an IAM instance profile using the role 'logstash' with a policy attached that has permissions to es:*
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "es:*"
            ],
            "Resource": "*"
        }
    ]
}
```

My LS version is 6.2.4
```
input {
    beats {
        port => 5044
    }
    syslog {
        port => 5514
    }
}
```
```
output {
      amazon_es {
        hosts => ["vpc-xxxx.us-east-1.es.amazonaws.com"]
        region => "us-east-1"
        index => "logstash-%{+YYYY.MM.dd}"
        }
}
```

**Comment by yogeshlandge** [comment] 2018-07-23 17:33
Facing the same issue, no updates in elasticsearch after "flushing output" debug log in logstash.

**Comment by pedroguima** [comment] 2018-08-24 10:16
I got it fixed by adding empty strings to the aws credentials config:
```
       aws_access_key_id => ''
       aws_secret_access_key => ''
```

**Comment by pingram3030** [comment] 2018-08-29 00:04
The symptoms sound like a similar problem I faced. The cause of the issue, for us, was that we were trying to ouput an object to a string. Logstash was sending
```
"host" : [ "name" : "foo.bar.com" ]
```
But, the ES template was expecting (the following output was gathered from `curl es/_template` (we use DNS CNAMEs because that's what sensible operators do))
```
"host": {
    "index": "false",
    "type": "text"
},
```
ES silently failed and the log message was instead stored with the super fast /dev/null storage engine.. To debug I recommend reviewing the ES template and putting this in to your output:
```
stdout { codec => rubydebug }
```
Then `journalctl -f -u logstash` to see the output as it streams in (with a minor delay) so you can compare what LS is sending to ES with what the template in ES is expecting. Noting that there is only a problem when there is a field previously defined in the template; adding new fields appears to JustWork™.

As for set up and configuration of ES it's not super clear for n00bs like myself, but FWIW our CF template is as follows:
* Note1: you have to put an access policy on to the ES domain as creating the policy else where didn't appear to work.
* Note2: you only need `es:ESHttp*` to push/pull data to/from ES, `es:*` is a touch aggressive and you probably shouldn't give all the things permission to modify your ES cluster.
* Note3: you can't use GetAttr as EsDomain doesn't exist when creating it to query it.. (knock knock, race condition, who's there?)
```
  EsDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:ESHttp*"
            Resource:
              Fn::Join:
                - ''
                - - "arn:aws:es:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":domain/"
                  - Ref: AWS::StackName
                  - "/*"
```
# The Real Bug
ES should be returning a 4xx when writing fails, which it normally does when logstash is using `logstash-output-elasticsearch` on a test ES server I ran. We used to custom roll an ES server, but are trying to switch to the AWS ES service.  So, it appears as thoguh the `logstash-output-amazon_es` plugin is the one not correctly handling ES rejecting the input.

**Comment by malpani** [comment] 2018-09-20 01:28
@pingram3030 - Thanks for sharing those insights. We have now updated the plugin to be in sync with `logstash-output-elasticsearch` which should address this

**Closed** 2019-10-10 20:50 UTC
