### ISSUE TITLE
Incompatible with Logstash >= 5.2.1

### ISSUE THREAD

**Issue by parasyte** [awslabs/logstash-output-amazon_es#51] opened 2017-02-15 00:11 UTC
Yay, dependency management!

This plugin has a dependency on an [old version of eleasticsearch](https://github.com/awslabs/logstash-output-amazon_es/blob/a34c29a82707d3a559fe3ba131df2a37328ad071/logstash-output-amazon_es.gemspec#L24). The current version is 5.2.1

The [`logstash-input-elasticsearch`](https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/7028b9733520cca04fac58d12fd43c7be7262582/logstash-input-elasticsearch.gemspec#L25) plugin (default plugin that ships with Logstash) depends on a more recent version. This change was made 7 days ago. Logstash 5.2.1 was released today.

```
Validating logstash-output-amazon_es
Installing logstash-output-amazon_es
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "elasticsearch":
  In snapshot (Gemfile.lock):
    elasticsearch (= 5.0.3)

  In Gemfile:
    logstash-input-elasticsearch (>= 0) java depends on
      elasticsearch (< 6.0.0, >= 5.0.3) java

    logstash-output-amazon_es (>= 0) java depends on
      elasticsearch (>= 1.0.10, ~> 1.0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.2.1)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.2.1) java

    logstash-output-amazon_es (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by threesquared** [comment] 2017-02-16 10:33
As a temporary workaround you can downgrade the version to `5.2.0` if you are using the official repository.

`sudo apt-get install logstash=1:5.2.0-1`

**Comment by parasyte** [comment] 2017-02-16 23:05
Yep, that's what we ended up doing a few days ago. Works a treat.

**Comment by bdo-aop** [comment] 2017-02-17 00:22
I really don't know or this is good solution, but it works for me now
I changed in file logstash-output-amazon_es.gemspec
`s.add_runtime_dependency 'elasticsearch', '~> 1.0', '>= 1.0.10'`
to
`s.add_runtime_dependency 'elasticsearch', ['>= 5.0.3', '< 6.0.0']`
after changes were applied, I rebuilt .gem **gem build logstash-output-amazon_es.gemspec**
and It was added into my logstash without any issues.
${LOGSTASH_PATH}/bin/logstash-plugin install logstash-output-amazon_es-1.1.0.gem.

**Comment by elssar** [comment] 2017-02-28 10:25
I'm getting this error with logstash `5.2.0` as well.  Is there an ETA on #53 getting merged?

**Comment by elssar** [comment] 2017-02-28 10:56
Please disregard the previous comment. There was a bug on my end where the logstash version was being overridden.

**Comment by bdo-aop** [comment] 2017-08-11 10:48
@phr3nzii This plugin works with 5.2(see my [comment](https://github.com/awslabs/logstash-output-amazon_es/issues/51#issuecomment-280509954) above)
I attached logstash-output-amazon_es-1.1.0.gem what is completly works with >5.2
[logstash-output-amazon_es-1.1.0.gem.zip](https://github.com/awslabs/logstash-output-amazon_es/files/1217603/logstash-output-amazon_es-1.1.0.gem.zip)

**Comment by malpani** [comment] 2017-08-12 00:39
Are you still facing problems? 

We should be good for any version < 6  after https://github.com/awslabs/logstash-output-amazon_es/commit/6dc56a09f6c14fc134828d02ede8f14b3e99d4fb 

Will close this issue after confirmation on the same

**Comment by phr3nzii** [comment] 2017-10-26 13:05
Apologies for the delay. I can confirm that this is working with Logstash 5.6.3

**Comment by AustinTag** [comment] 2019-10-10 21:34
Closing this issue due to inactivity and likely resolution in newer versions. Please re-open if problem persists.

**Closed by AustinTag** 2019-10-10 21:34 UTC
