### ISSUE TITLE
Logstash randomly stops flushing outgoing logs

### ISSUE THREAD

**Issue by artyom** [awslabs/logstash-output-amazon_es#6] opened 2015-10-10 09:12 UTC
I have a latest logstash installed on Debian Jessie (64bit):

```
logstash:
  Installed: 1:1.5.4-1
  Candidate: 1:1.5.4-1
  Version table:
 *** 1:1.5.4-1 0
        500 http://packages.elastic.co/logstash/1.5/debian/ stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

Plugin was installed by `bin/plugin install logstash-output-amazon_es` command. The configuration is following:

```
output {
    amazon_es {
        hosts => ["search-logs-.......us-west-1.es.amazonaws.com"]
        region => "us-west-1"
        aws_access_key_id => 'ACCESS_KEY'
        aws_secret_access_key => 'SECRET_KEY' 
        index => "logstash-%{+YYYY.MM.dd}"
    }
}
```

It points to a newly created AWS Elasticsearch cluster of 3 m3.medium nodes with 50 Gb EBS storage space each and default settings. This configuration worked for some hours, then logstash began logging the following exception:

```
{:timestamp=>"2015-10-10T09:10:14.785000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.1.0-java/lib/logstash/outputs/amazon_es.rb:324:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.1.0-java/lib/logstash/outputs/amazon_es.rb:316:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-amazon_es-0.1.0-java/lib/logstash/outputs/amazon_es.rb:349:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

Restart of logstash has no impact on this.

**Comment by owahlen** [comment] 2015-10-12 17:15
we have the same problem

**Comment by thinkspill** [comment] 2015-10-12 17:31
I was experiencing his as well during testing.

**Comment by lloydw** [comment] 2015-10-13 03:07
Same issue here

**Comment by malpani** [comment] 2015-10-13 06:45
I am trying to reproduce this - suspect from stack trace was some issue parsing bulk responses with error at http://git.io/vCEql , but I tried killing Elasticsearch on the backend host but the retries went through when automated restart of the process happened. 

Is there a sequence of steps taken to reproduce this or this was more like run for a few hours and the issue just occurs? Will continue to investigate more.

**Comment by thinkspill** [comment] 2015-10-13 06:47
It was nearly unavoidable for me. I think I was only briefly able to get data through to ES, and the rest of the time was hitting that error. I'll have to give it another shot soon. Maybe it was a transient launch week problem.

**Comment by malpani** [comment] 2015-10-13 07:00
This plugin (0.1.0) is also pretty new and likely to have unhandled cases and I will dig more into this tomorrow. 

Please do share your Elasticsearch domain details (domain-name and region) to "amazon-es-feedback@amazon.com" as it will help me debug better to see if this is a bug in the plugin (most likely) or there is some other issue.

**Comment by lloydw** [comment] 2015-10-13 23:34
@malpani I've managed to fix it by changing line 324 of amazon_es.ebs from:

if bulk_response["errors"]

to

if bulk_response["errors"] && bulk_response["items"]

Seems some results didn't have an items in the response. I think it was being triggered by attempting to send badly formated json (in my case the log was very large 10k+, suspecting this was bigger than the UDP packet size I was receiving it on and was being trimmed)

**Comment by sbuettner** [comment] 2015-10-14 15:35
It seems like the plugin does not recover after an error (compared to the official es output plugin). This leads to an logstash process which doesnt accept logs anymore.

**Comment by sbuettner** [comment] 2015-10-14 15:51
It seems like the plugin doesnt recover after several errors. This seems to block the logstash process.

### Steps to reproduce
Create a document with a new mapping using the `http` plugin:

```
curl -XPOST 192.168.99.100:8080 --header 'Content-Type: application/json' --data-binary '{"foo": {"bar": "baz"}}‘
```

Try to add another document with a different type to create an error message:

```curl  -XPOST 192.168.99.100:8080 --header 'Content-Type: application/json' --data-binary '{"foo": "othervalue"}‘```

Do this multiple times.

After you see the errors you should not be able to post new logs to the `http` plugin.

**Comment by JanAhrens** [comment] 2015-10-14 16:05
Here's a minimal logstash.conf for the situation that @sbuettner and I reproduced:

```
input {
  http {}
}

filter {}

output {
  amazon_es {
    hosts => ['XXXX']
    region => 'eu-west-1'
    aws_access_key_id => 'XXX'
    aws_secret_access_key => 'XXX'
    idle_flush_time => 1
  }
}
```

**Comment by malpani** [comment] 2015-10-15 00:00
Thanks @lloydw . That makes sense have pushed your suggestion in.

@sbuettner and @JanAhrens - I will try this as well. Were you hitting the same error trace? If so this change should fix it.

**Comment by JanAhrens** [comment] 2015-10-15 14:52
Hi @malpani,

We had the same issue and version 0.1.1 fixed it. Thanks for the fast response. I think you can close this issue.

Cheers, Jan

**Closed** 2015-10-15 21:47 UTC
Labels: bug

**Comment by Lifang13** [comment] 2016-07-01 20:06
The issue is still happening 
with version 1.0

**Comment by malpani** [comment] 2016-07-02 01:16
@Lifang13 could you please share more detailed config/trace and preferably steps to reproduce this.

**Comment by Lifang13** [comment] 2016-07-02 03:07
my logstash output config:

output {
    amazon_es {
        hosts => ["search-elk-prod-************kazoqhly.us-west-2.es.amazonaws.com"]
        region => "us-west-2"
    }
}

I do not know how to reproduce for you. I got the errors once a while. I had to restart the logstash to temporality fix it. 

i am thinking any output configuration can help l like reducing flush_size

**Comment by Lifang13** [comment] 2016-07-02 03:11
@malpani can you tell me the root cause for it

**Comment by funbrain** [comment] 2018-01-24 03:14
same issue.
for me ,sometimes logs are missing in ES
