### ISSUE TITLE
NoMethodError during plug installation

### ISSUE THREAD

**Issue by elster** [awslabs/logstash-output-amazon_es#172] opened 2021-10-26 19:23 UTC
When installing the plugin in combination with logstash 7.15.1 on RedHat Linux 7.9, this error occurs:
`[root@ip-10-143-26-46 logstash]# bin/logstash-plugin install --version 6.4.2 logstash-output-amazon_es
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating logstash-output-amazon_es-6.4.2
Resolving mixin dependencies
NoMethodError: undefined method 'error' for #<Gem::PlatformMismatch:0x789b3a77>
           fetch_plugin_dependencies at /usr/share/logstash/lib/bootstrap/bundler.rb:229
  expand_logstash_mixin_dependencies at /usr/share/logstash/lib/bootstrap/bundler.rb:212
                                each at org/jruby/RubyArray.java:1820
                            flat_map at org/jruby/RubyEnumerable.java:940
  expand_logstash_mixin_dependencies at /usr/share/logstash/lib/bootstrap/bundler.rb:212
  update_logstash_mixin_dependencies at /usr/share/logstash/lib/pluginmanager/install.rb:189
                             execute at /usr/share/logstash/lib/pluginmanager/install.rb:77
                                 run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:68
                             execute at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/subcommand/execution.rb:11
                                 run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:68
                                 run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-1.0.1/lib/clamp/command.rb:133
                              <main> at /usr/share/logstash/lib/pluginmanager/main.rb:64
[root@ip-10-143-26-46 logstash]# bin/logstash --version
Using bundled JDK: /usr/share/logstash/jdk
logstash 7.15.1`

**Comment by dlvenable** [comment] 2021-12-13 20:46
I'm closing this as a duplicate of #173.

**Closed by dlvenable** 2021-12-13 20:46 UTC
