### ISSUE TITLE
Bad "Need Help?" Link

### ISSUE THREAD

**Issue by mressler** [awslabs/logstash-output-amazon_es#49] opened 2017-01-21 14:17 UTC
The "Need Help?" section of the documentation links to https://discuss.elastic.co/c/logstash. However, when this plugin is mentioned there, the community states that this plugin is not supported: https://discuss.elastic.co/t/amazon-es-output-not-signing/72356

So, where should I go for help?

**Comment by markwalkom** [comment] 2017-01-22 01:14
To clarify, it's not supported by us at Elastic.
We refer these third party plugin problems to the author, in this case that is AWS :)

**Comment by msfroh** [comment] 2017-01-22 02:56
I'll update the Need Help? links to point somewhere more useful. In the meantime, I'll see if I can reproduce your problem.

**Comment by mressler** [comment] 2017-01-23 14:03
I can certainly help debug this issue. Let me know if there's any log information you'd like to see. I've been trying to track this down and it's the last thing I need to set up to feel good about my AWS ES configuration.

**Comment by mressler** [comment] 2017-01-27 16:49
Is there anything I can do to facilitate debugging this?

**Comment by msfroh** [comment] 2017-01-27 21:51
@mressler, can you clarify how you installed the plugin? Did you build from source or did you use "logstash-plugin install"?

Thanks!

**Comment by mressler** [comment] 2017-01-27 22:17
Here's what I ran, directly from my history:

```
sudo /opt/logstash/bin/logstash-plugin install logstash-output-amazon_es-1.0-java.gem
sudo /opt/logstash/bin/logstash-plugin install logstash-output-amazon_es
```

The first line is what I thought was intended based on the documentation:

> 3. Install plugin using <logstash-home>/bin/plugin install logstash-output-amazon_es-0.2.0-java.gem (or the non java variant)
> 4. For the 2.3 version , please use '/bin/logstash-plugin install logstash-output-amazon_es-1.0-java.gem'

But the second line is what ended up succeeding.

**Comment by msfroh** [comment] 2017-01-27 22:45
Okay, that should have installed version 1.0 of the plugin (which works with Logstash 2.3). You can confirm that by looking in $LOGSTASH_ROOT/vendor/bundle/jruby/1.9/gems/ for the logstash-output-amazon_es-1.0-java Gem.

Can you provide a **redacted** version of your config? (Remove your aws_access_key_id, aws_secret_access_key values, as well as your hosts).

For example, I have a working execution with the following redacted config:

```
output {
  amazon_es {
    hosts => ["REDACTED.us-east-1.es.amazonaws.com"]
    region => "us-east-1"
    aws_access_key_id => "REDACTED"
    aws_secret_access_key => 'REDACTED'
    index => "my-test-log-%{+YYYY.MM.dd}"
  }
}

input {
  file {
    path => ["/tmp/test-logs/*"]
  }
}
```

**Comment by mressler** [comment] 2017-07-06 16:17
Resurrecting this old issue because I still can't get this working. Presently the docs say:

    For 5.2 support, please use '/bin/logstash-plugin install logstash-output-amazon_es-2.0.1-java.gem'

And when I run that, I get:

    [ec2-user@ip-xxx logstash]$ sudo bin/logstash-plugin install logstash-output-amazon_es-2.0.1-java.gem
    Validating logstash-output-amazon_es-2.0.1-java.gem
    Plugin logstash-output-amazon_es-2.0.1-java.gem does not exist
    ERROR: Installation aborted, verification failed for logstash-output-amazon_es-2.0.1-java.gem

Running just `sudo bin/logstash-plugin install logstash-output-amazon_es` does get me version 1.0 - which the docs seem to suggest is supported for 2.3, but doesn't help me because...

I have torn down and rebuilt my whole Elasticsearch Service stack to be on ES5.3 thinking that would help me be up to date & more standard.

My redacted config looks like:
```
    input {
        file {
            path => "REDACTED"
            type => "log4j"
            codec => "json"
        }
    }
    filter {
        REDACTED
    }
    output {
        amazon_es {
            hosts => ["${LOGSTASH_HOST:REDACTED_DEFAULT_HOST}"]
            region => "us-east-1"
            # aws_access_key_id, aws_secret_access_key optional if instance profile is configured
            aws_access_key_id => '${ACCESS_KEY:REDACTED_DEFAULT_KEY}'
            aws_secret_access_key => '${SECRET_KEY:REDACTED_DEFAULT_SECRET}'
        }
    }
```

Is there a way to get a 5.3 supported version? I have my access key and secret in almost every listed place that this plugin states it is looking for them (the plugin config, all environment variables, credentials file), but my logstash log still lists:

    {:timestamp=>"2017-07-06T15:42:09.952000+0000", :message=>"[403] {\"Message\":\"User: anonymous is not authorized to perform: es:ESHttpGet on resource: REDACTED\"}", :class=>"Elasticsearch::Transport::Transport::Errors::Forbidden", :level=>:error}

Which suggests to me that it's still not signing requests. Or it's signing them and the signature has changed from 2.3 to 5.3?

**Comment by AustinTag** [comment] 2019-10-10 21:37
Closing this issue due to resolution of the issue.

**Closed by AustinTag** 2019-10-10 21:37 UTC
